### ISSUE TITLE
Reload doesn't work in dev environment

### ISSUE THREAD

**Issue by rex4539** [adityapk00/zecwallet-lite-electron#6]
Steps:
1. ```yarn dev```
2. Wallet -> Reload

What happened:
Screen becomes white.
```
injectGlobalHook.js:32 GET chrome-extension://react-developer-tools/build/backend.js net::ERR_UNKNOWN_URL_SCHEME
```

Expected result:
Content is reloaded.

**Comment by rex4539** [comment]
Applicable to both Zecwallet and Zecwallet lite.

**Comment by adityapk00** [comment]
Leftover boilerplate code, removed
