### ISSUE TITLE
Server info does not represent reality

### ISSUE THREAD

**Issue by rex4539** [adityapk00/zecwallet-lite-electron#8]
Steps:
Wallet -> Server info

What happened:
<img width="1411" alt="Screen Shot 2020-02-22 at 15 56 06" src="https://user-images.githubusercontent.com/227442/75093610-f8ba5e80-558b-11ea-9458-e6ff9ae44352.png">

Expected result:
"Connections" should show the actual connections the server's zcashd has.
"Network Solution Rate" should show the actual rate taken from the server's zcashd.

**Comment by adityapk00** [comment]
The lightwalletd server doesn't return the connections or sols/s, so I removed them
